### PR TITLE
Unbreak table describing loadConfig parameters

### PR DESCRIPTION
**Pull request by ptcher**
In short-form markdown tables, line breaks are interpreted as starting a new cell row, so each row must be written in one line of text.
For tables with longer content, it seems like the full HTML form is more appropriate.

### CODE REVIEW

**Comment by colinbdclark** [comment]
ok to test

**Comment by amb26** [comment]
Mysterious, rather basic provisioning failure:
````
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
````

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
Genuine linting failure:
````
Running "wrapped-markdownlint:src" (wrapped-markdownlint) task
Warning: 
/home/vagrant/kettle/docs/ConfigsAndApplications.md: 122: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
/home/vagrant/kettle/docs/ConfigsAndApplications.md: 123: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
 Used --force, continuing.
````

**Comment by ptcher** [comment]
I removed the trailing spaces caught by the linter, and [fixed a broken link in another docs file](https://github.com/fluid-project/kettle/pull/59/commits/9ac4041a54b5ab045024a7a2a65c4a41cdb37533). Considering it minor and related enough it can be included in this PR.

**Pull request merged**
