### PR TITLE
KETTLE-92: Restored kettle.test.request.http handling of url option and updated dependencies with linting

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by amb26** [comment]
Hi there @the-t-in-rtf - could you take a look at this for me since I am getting a linting error inside the markdown with fluid-grunt-lint-all 2.0.0 which complains

````
E:\source\gits\kettle\docs\DataSources.md
  48:5  error  'fluid' is already defined as a built-in global variable  no-redeclare

E:\source\gits\kettle\docs\KettleTestingFramework.md
  545:5  error  'fluid' is already defined as a built-in global variable  no-redeclare
````

Thanks!

**Comment by the-t-in-rtf** [comment]
I encountered the same thing in my own downstream work, but didn't want to disable the rules globally.  Here's a config snippet to add to your `.fluidlintallrc.json` and defang that check:

```
    "eslint": {
        "md": {
            "options": {
                "overrideConfig": {
                    "rules": {
                        "no-redeclare": 0
                    }
                }
            }
        }
    }
```

**Comment by amb26** [comment]
Thanks, that was very helpful, although somehow I had to remove the "overrideConfig" layer of wrapping in order to make this work - I don't know why.
Note that I am still on fluid-grunt-lint-all since I am trying to change just one thing at a time.
One final problem I have is the warning
````
Running "wrapped-eslint:js" (wrapped-eslint) task
E:\source\gits\kettle\tests\configs\node_modules\test-module\index.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override
````
I'm unable to make it go away by updating the "ignores" option as the docs suggest - any ideas?

**Comment by the-t-in-rtf** [comment]
> Thanks, that was very helpful, although somehow I had to remove the "overrideConfig" layer of wrapping in order to make this work - I don't know why.

Either we wrap the options differently in the new world or that option was added in a newer version of ESLint than was used by our grunt infrastructure.

> I'm unable to make it go away by updating the "ignores" option as the docs suggest - any ideas?

I'll have to refresh my memory about how we handle the layering of ignores and "unignores" in fluid-glob, if we can fix it anywhere it's probably more doable with the new plugin.

**Pull request merged**
